### ISSUE TITLE
Async Fix

### ISSUE THREAD

**Issue by ldrach** [ldrach/Comp3160-CarPoolProject#17]
Issues with async tasks

**Comment by vandor5676** [comment]
https://github.com/ldrach/Comp3160-CarPoolProject/blob/6df50e9232fcd0f2d7fa93d038383b4448f009d3/app/src/main/java/com/example/carpoolapp/FireStoreDatbase.java#L45

onSuccess is asynchronous

**Comment by vandor5676** [comment]
https://github.com/ldrach/Comp3160-CarPoolProject/blob/9b67b176e643e62e477b794962358edd88441bce/app/src/main/java/com/example/carpoolapp/LoginActivity.java#L329

This is currently my fix for the async problem but its bad and needs to be changed or worked around possibly with  shared preferences
